var champs = [
	{name:"Annie"}
];

var postes = [
	"TOP", "MID", "SUP", "ADC", "JUN"
];

var list_champ = [
    {name:'Aatrox', lanes: ['top','jun'], image:'aatrox.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Ahri', lanes: ['mid'], image:'ahri.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Akali', lanes: ['mid','top'], image:'akali.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Alistar', lanes: ['sup','jun','top'], image:'alistar.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Amumu', lanes: ['jun','top'], image:'amumu.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Anivia', lanes: ['mid'], image:'anivia.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Annie', lanes: ['mid','sup'], image:'annie.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Ashe', lanes: ['adc'], image:'ashe.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Azir', lanes: ['mid','sup','top'], image:'azir.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Blitzcrank', lanes: ['sup'], image:'blitzcrank.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Brand', lanes: ['mid'], image:'brand.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Braum', lanes: ['sup'], image:'braum.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Caitlyn', lanes: ['adc'], image:'caitlyn.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Cassiopeia', lanes: ['mid'], image:'cassiopeia.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Cho'Gath", lanes: ['top','jun'], image:'chogath.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Corki', lanes: ['adc'], image:'corki.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Darius', lanes: ['top','jun'], image:'darius.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Diana', lanes: ['mid','jun'], image:'diana.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Dr.mundo', lanes: ['top','jun'], image:'DrMundo.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Draven', lanes: ['adc'], image:'draven.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Elise', lanes: ['jun'], image:'elise.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Evelynn', lanes: ['jun'], image:'evelynn.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Ezreal', lanes: ['mid','adc'], image:'ezreal.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Fiddlesticks', lanes: ['jun','mid','sup'], image:'fiddlesticks.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Fiora', lanes: ['top','jun'], image:'fiora.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Fizz', lanes: ['mid'], image:'fizz.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Galio', lanes: ['mid','sup'], image:'galio.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Gangplank', lanes: ['top'], image:'gangplank.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Garen', lanes: ['top'], image:'garen.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Gnar', lanes: ['top'], image:'gnar.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Gragas', lanes: ['mid','sup','top'], image:'gragas.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Graves', lanes: ['adc'], image:'graves.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Hecarim', lanes: ['jun'], image:'hecarim.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Heimerdinger', lanes: ['mid','sup'], image:'heimerdinger.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Irelia', lanes: ['top','jun'], image:'irelia.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Janna', lanes: ['sup'], image:'janna.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'JarvanIV', lanes: ['jun','top'], image:'jarvaniv.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Jax', lanes: ['top','jun'], image:'jax.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Jayce', lanes: ['top'], image:'jayce.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Jinx', lanes: ['adc'], image:'jinx.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Kalista', lanes: ['adc'], image:'kalista.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Karma', lanes: ['mid','sup'], image:'karma.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Karthus', lanes: ['mid'], image:'karthus.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Kassadin', lanes: ['mid'], image:'kassadin.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Katarina', lanes: ['mid'], image:'katarina.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Kayle', lanes: ['mid','top','sup'], image:'kayle.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Kennen', lanes: ['mid','sup','top'], image:'kennen.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Kha'Zix", lanes: ['jun'], image:'khazix.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Kog'Maw", lanes: ['mid','adc'], image:'kogmaw.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'LeBlanc', lanes: ['mid'], image:'leblanc.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Lee Sin", lanes: ['top','jun'], image:'leesin.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Leona', lanes: ['sup'], image:'leona.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Lissandra', lanes: ['mid'], image:'lissandra.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Lucian', lanes: ['adc'], image:'lucian.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Lulu', lanes: ['top','sup','mid'], image:'lulu.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Lux', lanes: ['mid','sup'], image:'lux.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Malphite', lanes: ['top','jun'], image:'malphite.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Malzahar', lanes: ['mid'], image:'malzahar.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Maokai', lanes: ['top','jun','sup'], image:'maokai.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Master Yi", lanes: ['top','jun','mid'], image:'masteryi.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Miss Fortune", lanes: ['adc'], image:'missfortune.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Mordekaiser', lanes: ['top','mid'], image:'mordekaiser.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Morgana', lanes: ['mid','sup'], image:'morgana.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nami', lanes: ['sup'], image:'nami.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nasus', lanes: ['top','jun'], image:'nasus.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nautilus', lanes: ['top','jun'], image:'nautilus.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nidalee', lanes: ['mid','sup','top'], image:'nidalee.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nocturne', lanes: ['top','jun'], image:'nocturne.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Nunu', lanes: ['sup','top','jun'], image:'nunu.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Olaf', lanes: ['top','jun'], image:'olaf.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Orianna', lanes: ['mid','sup'], image:'orianna.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Pantheon', lanes: ['top','jun'], image:'pantheon.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Poppy', lanes: ['top','sup'], image:'poppy.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Quinn', lanes: ['adc','top'], image:'quinn.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Rammus', lanes: ['jun','top'], image:'rammus.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Rek'Sai", lanes: ['jun','top'], image:'reksai.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Renekton', lanes: ['mid','top'], image:'renekton.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Rengar', lanes: ['top','jun'], image:'rengar.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Riven', lanes: ['jun','top','mid'], image:'riven.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Rumble', lanes: ['top'], image:'rumble.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Ryze', lanes: ['mid','sup','top'], image:'ryze.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Sejuani', lanes: ['jun','sup'], image:'sejuani.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Shaco', lanes: ['jun'], image:'shaco.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Shen', lanes: ['top','jun'], image:'shen.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Shyvana', lanes: ['top','jun'], image:'shyvana.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Singed', lanes: ['top','jun'], image:'singed.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Sion', lanes: ['top','jun'], image:'sion.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Sivir', lanes: ['adc'], image:'sivir.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Skarner', lanes: ['top','jun'], image:'skarner.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Sona', lanes: ['mid','sup'], image:'sona.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Soraka', lanes: ['mid','sup'], image:'soraka.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Swain', lanes: ['mid'], image:'swain.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Syndra', lanes: ['mid'], image:'syndra.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Talon', lanes: ['mid','top'], image:'talon.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Taric', lanes: ['sup'], image:'taric.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Teemo', lanes: ['mid','sup','top'], image:'teemo.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Thresh', lanes: ['sup'], image:'thresh.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Tristana', lanes: ['mid','adc'], image:'tristana.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Trundle', lanes: ['top','jun'], image:'trundle.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Tryndamere', lanes: ['top','jun'], image:'tryndamere.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Twistedfate', lanes: ['mid'], image:'twistedfate.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Twitch', lanes: ['adc'], image:'twitch.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Udyr', lanes: ['top','jun'], image:'udyr.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Urgot', lanes: ['adc'], image:'urgot.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Varus', lanes: ['adc'], image:'varus.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Vayne', lanes: ['adc','top'], image:'vayne.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Veigar', lanes: ['mid'], image:'veigar.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Vel'Koz", lanes: ['mid'], image:'velkoz.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Vi', lanes: ['top','jun'], image:'vi.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Viktor', lanes: ['mid'], image:'viktor.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Vladimir', lanes: ['top'], image:'vladimir.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Volibear', lanes: ['top','jun'], image:'volibear.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Warwick', lanes: ['top','jun'], image:'warwick.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Wukong', lanes: ['top','jun'], image:'wukong.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Xerath', lanes: ['mid'], image:'xerath.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:"Xin Zhao", lanes: ['top','jun'], image:'xinzhao.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Yasuo', lanes: ['top','mid'], image:'yasuo.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Yorick', lanes: ['top'], image:'yorick.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Zac', lanes: ['top','jun'], image:'zac.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Zed', lanes: ['mid','top'], image:'zed.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Ziggs', lanes: ['mid'], image:'ziggs.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Zilean', lanes: ['mid','sup'], image:'zilean.png', counters:'Apply heal reduction, Hard CC', use:'false'},
    {name:'Zyra', lanes: ['mid','sup'], image:'zyra.png', counters:'Apply heal reduction, Hard CC', use:'false'}
];